package bgu.spl.net.impl.stomp;

public enum LoginAttemptResponseType {
    ERR_CLIENT_ALREADY_CONNECTED, SUCCESS_LOGIN_USER_CREATED, ERR_USER_ALREADY_CONNECTED, SUCCESS_LOGIN_USER_EXISTS, ERR_WRONG_PASSWORD 
}
